// GENERATED by scripts/gen-version.mjs — do not edit by hand.
// Run `npm run gen-version` (also runs on `prebuild`). The lockstep test in
// tests/version.test.ts pins this to package.json.version.
export const PLUGIN_VERSION = "0.2.7"
